name: Atualiza VM com o Docker

on:
  push:
    branches:
      - main

jobs:
  update-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build e push Docker image
      run: |
        docker buildx create --name docker-builder
        docker buildx use docker-builder
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ github.repository }}:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ github.repository }}:latest
